kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  selector:
    environment: dev
    component: backend
    project: expense
    version: "1.0.0"
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80
---
kind: Pod
apiVersion: v1
metadata:
  name: backend
  labels:
    environment: dev
    component: backend
    project: expense
    version: "1.0.0"
spec:
  containers:
    - name: nginx
      image: nginx
    
