apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: nginx
  #-- Replicaset labels
  labels:
    app: frontend
    tier: web
spec:
  ## Replicaset use these labels to find the pods for creating desired number of replicas
  replicas: 3
  selector:
    matchLabels:
      app: frontend
      tier: web
  ##-- Pod definition internally.
  template:
    metadata:
      labels:
        app: frontend
        tier: web
    spec:
      containers:
        - name: nginx
          image: nginx:stable-perl
      
